### ISSUE TITLE
is the scroll button supposed to be invisible or not 

### ISSUE THREAD

**Issue by Cythrex** [warrayquipsome/Chillax#11]
idk, the scroll button is invisible on all things

**Comment by milkembers** [comment]
yes, it is supposed to be

**Comment by warrayquipsome** [comment]
yep its suppose to be transparent, i made it so it looks a bit mroe cleaner

**Comment by PixelHir** [comment]
is it possible to make it optional? For me the scrollbar is totally invisible
![image](https://github.com/warrayquipsome/Chillax/assets/7670940/8f9e7450-ff09-4cc9-b40d-303826b928c6)
