### ISSUE TITLE
Working with Vencord

### ISSUE THREAD

**Issue by ToonsV2** [warrayquipsome/Chillax#12]
(sorry if I'm in the wrong place, new to this website) Can this work with Vencord because my Betterdiscord can't do themes (don't know why) so I switched to Vencord, only to copy and pasted the .css link in and to get a really glitched theme. I asked around and it's apparently because of 'hardcoded class names'. Please make this compatible with Vencord, this is my favourite theme right now,

**Comment by milkembers** [comment]
it is compatible, you just have to grab the direct link to chillax.theme.css

**Comment by fowlis** [comment]
> my Betterdiscord can't do themes

I'm very late to this, but can you give more info as to why? I've rarely seen BD struggle with theming.

**Comment by blyad2137** [comment]
It's not Vencord fault, or at least I think it isn't.

**Comment by PixelHir** [comment]
Vencord user here, workaround seems to be importing the theme into openasar instead of Vencord itself
