### ISSUE TITLE
Discord is unable to return to homepage after entering settings

### ISSUE THREAD

**Issue by ceraph1m** [warrayquipsome/Chillax#15]
This mod runs okay, but I cannot find a way back onto the homepage after clicking settings. Also unable to find any esc or X button like there usually is. Is there another way to exit or is this a bug?

Also, the dark mode doesn't work, even if I remove other links and set it up individually.

The top half of - o x is also cut off. Mildly buggy.

I appreciate your work :) Other than that, the mod looks great!

**Comment by BOBebomb** [comment]
click next to the settings page
