### ISSUE TITLE
Possible Bug.

### ISSUE THREAD

**Issue by Ipertatos** [warrayquipsome/Chillax#19]
I dont know if this issue is because of any mods (it shouldn't) but sometimes when I enter a chat that has new messages it just scrolls a random amount upwards and I have to scroll down manually to see the new messages. sometimes its just 2 scrolls up sometimes it goes up to the beginning of the chat. This is on BetterDiscord on windows on release discord version.

**Comment by WereWolfix** [comment]
Yea I have the same problem. The "buttom" to scroll all the way down is also missing
