### ISSUE TITLE
from: doesn't show up in the search parameters

### ISSUE THREAD

**Issue by reasonings** [warrayquipsome/Chillax#41]
![image](https://github.com/warrayquipsome/Chillax/assets/148498854/2066219a-ca5f-4fd9-9ec9-b53b256a4955)

**Comment by Inmoresentum** [comment]
Can you please add a bit more info like the **steps to reproduce**, which version of Chillax (have you applied any customization) of you are using, which client mod, which version of discord you are on (_PTB, Canary & Stable_)? Thanks.

On a side note `from:` does show up (_see the attach screenshot_), I have tested this on a fresh vanilla Chillax with fresh discord (_stable_).


![image](https://github.com/warrayquipsome/Chillax/assets/64426953/9e004b99-acfd-4101-8d5c-37b05922ca77)

**Comment by reasonings** [comment]
Alright I just figured out why it did that. For some reason, streamer mode was enabled (with no banned, I must have closed it). Removing the streamer mode fixed the problem.
