### ISSUE TITLE
Its broken

### ISSUE THREAD

**Issue by walmarr** [warrayquipsome/Chillax#43]
In the newest version it doesnt work, Just like the home tab etc. Could you fix it please?

**Comment by Inmoresentum** [comment]
Please provide more information regarding your issue for us to reproduce. For instance, which client mod, which version of discord including stable, PTB  or canary. Furthermore, if possible please provide screen shots for easy identification. Thanks as always.

**Comment by Inmoresentum** [comment]
Resolved in discord server.
