### ISSUE TITLE
what is new update?

### ISSUE THREAD

**Issue by leonglo** [warrayquipsome/Chillax#5]
What is new in the update? could you add releases?

**Comment by warrayquipsome** [comment]
hey im sorry that i cant make a releases of what has been updated as its very annoying to have to keep adding it but you can join the support server and look for the announcement channel as i sometimes have let all of us know what will be coming in the new versions

**Comment by leonglo** [comment]
Sure! Do you have a link for your discord server? I can't click on the one on the page
