### ISSUE TITLE
How can i change text highlight color?

### ISSUE THREAD

**Issue by neko4322** [warrayquipsome/Chillax#52]
As in title, the default color is too bright. May I and how to change it?

**Comment by Inmoresentum** [comment]
Hi!
I don't exactly understand what do you mean by the `text highlight color`. However, please [click on this link](https://github.com/warrayquipsome/Chillax/blob/main/Docs/FAQs.md#4-how-to-change-the-accent-color-the-below-red-thingpart-see-attached-screenshot) and see if this what you are looking for or not. If this is not the case then please provide a screenshot and more details here in this thread. You can also knock us [discord](https://discord.com/invite/DrfX6286kF) if you like. TIA)

**Comment by neko4322** [comment]
![image](https://github.com/user-attachments/assets/870cb53b-3d16-430e-8f0b-e072ba5cc080)
It's the color of the highlight when select text.

**Comment by Inmoresentum** [comment]
@neko4322 Please follow the instructions give in [here](https://github.com/warrayquipsome/Chillax/blob/main/Docs/FAQs.md#4-how-to-change-the-accent-color-the-below-red-thingpart-see-attached-screenshot). Basically you will have to change the accent colors and this should do the job.

**Comment by neko4322** [comment]
omg it works!!
i didn't change both rgb and hex, now i do.
thanks for your time and great work!

**Comment by Inmoresentum** [comment]
For other issues please knock us on discord for the fastest possible response :)
