### ISSUE TITLE
Пропало свечение сообщений

### ISSUE THREAD

**Issue by Sangrennn** [warrayquipsome/Chillax#53]
Год назад тема chillax работала у меня отлично потом я переустановил дискорд и через полгода сейчас поставил снова вашу тему и там пропало свечение сообщений
![Screenshot_1](https://github.com/user-attachments/assets/84895d32-4feb-4fb7-a77b-b74c3f9bf0ca)
![Screenshot_2](https://github.com/user-attachments/assets/584551c5-1e90-4c36-bc1a-bd040b7e30d7)
![Screenshot_3](https://github.com/user-attachments/assets/dd5caef7-4a36-430d-b5c3-2d5382df07c2)

**Comment by Inmoresentum** [comment]
Hi! Please provide us with more details. For instance, which client mod you are using, which version of chillax etc. TIA!

**Comment by Inmoresentum** [comment]
@Sangrennn Any update on this?

**Comment by Inmoresentum** [comment]
No response. Hence closing the issue as stale.
