### ISSUE TITLE
Prevent Memberlist from Collasping

### ISSUE THREAD

**Issue by angsaysroar** [warrayquipsome/Chillax#6]
Is it possible to get a copy of the theme with the memberlist static? I would prefer that the memberlist NOT collapse. Thanks!

**Comment by warrayquipsome** [comment]
sorry for the late reply but in the theme settings you can find a part to remove the addon 
![image](https://user-images.githubusercontent.com/84565593/219921677-c26224fa-f91d-46d4-b20a-d0c429e1d81f.png)

**Comment by angsaysroar** [comment]
> sorry for the late reply but in the theme settings you can find a part to remove the addon ![image](https://user-images.githubusercontent.com/84565593/219921677-c26224fa-f91d-46d4-b20a-d0c429e1d81f.png)

No worries, and thank you! 

Can you let me know what the CSS class or ID is for blockquotes? I'd like to change it from red and make it more of a gray background. [](https://i.imgur.com/k9NPKwy.png)

I appreciate your help and time. Thank you!

**Comment by warrayquipsome** [comment]
Isn't block quotes in discord like the
```css
.class{somethhing}
```
The block quotes on chillax is half transparent black isn't it?

**Comment by angsaysroar** [comment]
> Isn't block quotes in discord like the
> 
> ```css
> .class{somethhing}
> ```
> 
> The block quotes on chillax is half transparent black isn't it?

Okay, it doesn't appear to be blockquote, but user mentions. Here is a screenshot: https://i.imgur.com/ECFFuBJ.png
