### ISSUE TITLE
Theme doesn't jump to latest message in channels 

### ISSUE THREAD

**Issue by Derpmore** [warrayquipsome/Chillax#7]
Most channels I click on with new messages I have to spam end button to get to latest message. These are channels I get new messages in frequently so its not a channel I decided to click in on after multiple days, it happens multiple times per day. It's both pings, normal messages and bot messages.

**Comment by warrayquipsome** [comment]
i have this issue as well but i think its just a discord problem cus using normal discord without the theme it also happens for me so idrk
