### ISSUE TITLE
Make the friends list even / Show username + icons at all time

### ISSUE THREAD

**Issue by iced-capp** [warrayquipsome/Chillax#8]
![image](https://user-images.githubusercontent.com/117924373/224381282-d0c99122-e926-48c3-963e-6026f2558857.png)
If there is an option to make the friends list even, please let me know because this bugs me a bit haha. 
![image](https://user-images.githubusercontent.com/117924373/224381645-85ad9b0e-06b5-4908-9a47-1f50b2d2efca.png)
Also is there a way to show the username and the mute/deafen icons at the same time?

**Comment by warrayquipsome** [comment]
1st issue - im not sure how and why is it like that 
2nd issue - no because the margin is small

**Comment by warrayquipsome** [comment]
for the avatar on issue 1 im gonna make it big again, discord updates smh
